language: python
python:
  - "3.4"
install:
  - "pip install -r requirements.txt"
  - "pip install -r test-requirements.txt"
  - "python3 setup.py install"
script: nosetests wazo_admin_ui
notifications:
  email:
    recipients:
      - dev+tests-reports@wazo.community
    on_success: change
    on_failure: change
branches:
  only:
    - master
sudo: false
