# This file should not be modified as it may get changed by the maintainer.
# Add extra configuration files in the extra_config_files directory to override
# the content from this file

# Extra configuration directory where the config files overriding this file
# should be.
extra_config_files: /etc/wazo-admin-ui/conf.d/

# Change the log level to debug level.
debug: false

# Log file.
log_filename: /var/log/wazo-admin-ui.log

# PID file.
pid_filename: /var/run/wazo-admin-ui/wazo-admin-ui.pid

https:
  listen: 0.0.0.0
  port: 9296
  certificate: /usr/share/xivo-certs/server.crt
  private_key: /usr/share/xivo-certs/server.key

# wazo-auth connection information
auth:
  host: localhost
  port: 9497
  verify_certificate: /usr/share/xivo-certs/server.crt

# xivo-confd connection information
confd:
  host: localhost
  port: 9486
  verify_certificate: /usr/share/xivo-certs/server.crt

# wazo-call-logd connection information
call_logd:
  host: localhost
  port: 9298
  verify_certificate: /usr/share/xivo-certs/server.crt

# wazo-plugind connection information
plugind:
  host: localhost
  port: 9503
  verify_certificate: /usr/share/xivo-certs/server.crt
