extra_config_files: /etc/wazo-admin-ui/conf.d/

debug: false
log_filename: /var/log/wazo-admin-ui.log
pid_filename: /var/run/wazo-admin-ui/wazo-admin-ui.pid

https:
  listen: 0.0.0.0
  port: 9296
  certificate: /usr/share/xivo-certs/server.crt
  private_key: /usr/share/xivo-certs/server.key
